version: "3.4"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3307:3308
    environment:
      MYSQL_DATABASE: it_support_db
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db:/var/lib/mysql
volumes:
  db: